### ISSUE TITLE
 Remove topological sort 

### ISSUE THREAD

**Issue by 89z** [momchil-velikov/go-intro-algorithms#1]
I see a mention in the Readme, but its not actually been implemented anywhere

**Comment by momchil-velikov** [comment]
Hi,

It's implemented here:

https://github.com/momchil-velikov/go-intro-algorithms/blob/c2900b72191ecc6633c6982c5e0d145a483f435a/Graphs/src/dfs/dfs.go#L202

The function `topSort` returns the reverse of the post-order traversal of the graph.
